import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Gradient from "@/components/Gradient";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tasker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Gradient />
        {children}
      </body>
    </html>
  );
}
